### ISSUE TITLE
m6502 @ 3d0d0f1 - Error 404

### ISSUE THREAD

**Issue by makertobi** [pyrex8/pico-iie#1]
@pyrex8 
c6502.c not available. Fatal Error: Remote branch master not found in upstream origin. Can't compile the Pico c/c++-code.
It looks like https://github.com/pyrex8/m6502.git was removed from Github. Please provide it again

**Comment by pyrex8** [comment]
I apologize. I had it as a private repo. Please let me know it this fixes the issue.

**Comment by pyrex8** [comment]
I somehow missed your original comment. I didn't realize I had left the
repo as private. I hope this fixes the problem.

**Comment by pyrex8** [comment]
Changed  https://github.com/pyrex8/m6502.git from private to public.

**Comment by makertobi** [comment]
Perfect. It worked. Thank You.
