### ISSUE TITLE
Could this be standalone?

### ISSUE THREAD

**Issue by EDKGames1** [pyrex8/pico-iie#2]
I wonder if you could mod this, so you could load files from an SD card and use a keyboard for control. Has anyone done anything like that?
Thanks in advance.

**Comment by pyrex8** [comment]
I tried to make this as modular as possible so that adding a keyboard interface and possibly an SD card reader would be possible. I am working on a more stand alone version of the hardware and software. I don't have any hard dates since this project is just for fun.

**Comment by EDKGames1** [comment]
I was just wondering if I connected a keyboard and screen to the Pico if it would display and take input.

**Comment by EDKGames1** [comment]
Could it do that?

**Comment by pyrex8** [comment]
I'm not sure about USB keyboards and HDMI output. You can always fork the project and customize it to your needs.

**Comment by EDKGames1** [comment]
Ok. I could modify it, but I don't have the skill to do a Video
out/keyboard in/sd card modification. I'll just wait for your release, or
go a diffrent route.
Thanks.
